import Head from 'next/head';
import Link from "../Link";
import NextLink from 'next/link';

import styles from './NavBar.module.scss';

export default function NavBar() {
    return (
        <>
            <Head>
                <title>Gestão Técnica</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header className={styles.header}>
                <div>
                    <button className={styles.btn}>
                        <NextLink href="/">
                            <div className={styles.iconContainer}>
                                <img src='assets/icons/home.svg' className={styles.img} alt="Home" />
                            </div>
                        </NextLink>
                    </button>
                    <h3>home</h3>
                </div>

                <div>
                    <button className={styles.btn}>
                        <NextLink href="/HomeLista">
                            <div className={styles.iconContainer}>
                                <img src='assets/icons/list.svg' className={styles.img} alt="Lista de presença" />
                            </div>
                        </NextLink>
                    </button>
                    <h3>gerir de dados</h3>
                </div>

                <div>
                    <button className={styles.btn}>
                        <NextLink href="/HomeMVS">
                            <div className={styles.iconContainer}>
                                <img src='assets/icons/mvs.svg' className={styles.img} alt="MVS" />
                            </div>
                        </NextLink>
                    </button>
                    <h3>MVS</h3>
                </div>

                {/* <Link className={styles.link} text={'Lista de presença'} href={'/Lista'} /> */}
                {/* <Link className={styles.link} text={'MVS'} href={'/HomeMVS'} /> */}
            </header>
        </>
    )
}

